[project]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "hunter_copy"
platforms = ["linux-64"]
version = "0.1.3"

[tasks]
test = "mojo hunter_copy.mojo test/query.csv test/search test/found"
build = "mojo build hunter_copy.mojo -o dist/hunter_copy;cd dist; sha256sum hunter_copy > sha256sum.hunter_copy.txt"

[dependencies]
max = ">=25.1.0,<26"
#find_substring = "0.1.1"
#mojo_csv = "1.2.0"
