[project]
authors = ["Josh S Wilkinson <joshswilkinson@pm.me>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "hunter_copy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo hunter_copy.mojo test/query.csv test/search test/found"
build = "mojo build hunter_copy.mojo -o dist/hunter_copy"


[dependencies]
max = ">=24.6.0,<25"
